Size:
  width: 400
  height: 400
  cell_size: 50

Pieces:
  white:
    king: resources/images/pieces/pieces-basic/white-king.png
    queen: resources/images/pieces/pieces-basic/white-queen.png
    bishop: resources/images/pieces/pieces-basic/white-bishop.png
    knight: resources/images/pieces/pieces-basic/white-knight.png
    rook: resources/images/pieces/pieces-basic/white-rook.png
    pawn: resources/images/pieces/pieces-basic/white-pawn.png
  black:
    king: resources/images/pieces/pieces-basic/black-king.png
    queen: resources/images/pieces/pieces-basic/black-queen.png
    bishop: resources/images/pieces/pieces-basic/black-bishop.png
    knight: resources/images/pieces/pieces-basic/black-knight.png
    rook: resources/images/pieces/pieces-basic/black-rook.png
    pawn: resources/images/pieces/pieces-basic/black-pawn.png