Size: 64

Pieces paths:
  white:
    king: resources/images/pieces/pieces-basic-png/white-king.png
    queen: resources/images/pieces/pieces-basic-png/white-queen.png
    bishop: resources/images/pieces/pieces-basic-png/white-bishop.png
    knight: resources/images/pieces/pieces-basic-png/white-knight.png
    rook: resources/images/pieces/pieces-basic-png/white-rook.png
    pawn: resources/images/pieces/pieces-basic-png/white-pawn.png
  black:
    king: resources/images/pieces/pieces-basic-png/black-king.png
    queen: resources/images/pieces/pieces-basic-png/black-queen.png
    bishop: resources/images/pieces/pieces-basic-png/black-bishop.png
    knight: resources/images/pieces/pieces-basic-png/black-knight.png
    rook: resources/images/pieces/pieces-basic-png/black-rook.png
    pawn: resources/images/pieces/pieces-basic-png/black-pawn.png