Playe's Turn: white
a1: white rook
a2: white pawn
a7: black pawn
a8: black rook
b1: white knight
b2: white pawn
b7: black pawn
b8: black knight
c1: white bishop
c2: white pawn
c7: black pawn
c8: black bishop
d1: white queen
d2: white pawn
d7: black pawn
d8: black queen
e1: white king
e2: white pawn
e7: black pawn
e8: black king
f1: white bishop
f2: white pawn
f7: black pawn
f8: black bishop
g1: white knight
g2: white pawn
g7: black pawn
g8: black knight
h1: white rook
h2: white pawn
h7: black pawn
h8: black rook
